build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=tests/JCFirebaseTest.php
                coverage:
                    file: JCFirebaseTest.php
                    format: php-clover