tools:
    external_code_coverage: true
build:
    environment:
            php:
                version: 5.6
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'